version: '3'

services:
    unitree_melodic:
        privileged: true
        image: "unhcarl/unitree-melodic:latest"
        network_mode: host
        environment:
            - ROS_MASTER_URI=$ROS_MASTER_URI
            - ROS_IP=$ROS_IP
            - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix/:/tmp/.X11-unix/
        #tty: true
        command: /tmp/unitree_launch.bash
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]

