version: '3'

services:
    ros_noetic_humble_src:
        privileged: true
        image: "unhcarl/ros-noetic-humble-src:latest"
        network_mode: host
        environment:
            - ROS_MASTER_URI=$ROS_MASTER_URI
            - ROS_IP=$ROS_IP
            - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix/:/tmp/.X11-unix/
        tty: true
           
